spring:
  datasource:
    base:
      jdbc-url: jdbc:mysql://localhost:3306/base_admin_api?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&maxReconnects=10&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
      username: root
      password: root
