server:
  port: 8888
spring:
  profiles:
    include:
      - common
      - file
      - base
      - core

### 日志等级
logging:
  level:
    org:
      humki: debug


admin:
  config:
    resource-locations:
      - C:\Users\Admin\Desktop\aaa\angular